#bridge-file-version: #25
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_acacia -1 setblock ~1 ~ ~ dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_acacia -1 setblock ~-1 ~ ~ dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_acacia -1 setblock ~1 ~ ~ dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_acacia -1 setblock ~ ~ ~1 dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_acacia -1 setblock ~ ~ ~-1 dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_acacia -1 setblock ~ ~ ~1 dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_acacia -1 setblock ~ ~ ~ dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_acacia -1 setblock ~ ~ ~ dbc:top_table_acacia
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_acacia -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_acacia -1 setblock ~ ~ ~ dbc:top_table_acacia
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_oak -1 setblock ~1 ~ ~ dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_oak -1 setblock ~-1 ~ ~ dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_oak -1 setblock ~1 ~ ~ dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_oak -1 setblock ~ ~ ~1 dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_oak -1 setblock ~ ~ ~-1 dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_oak -1 setblock ~ ~ ~1 dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_oak -1 setblock ~ ~ ~ dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_oak -1 setblock ~ ~ ~ dbc:top_table_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_oak -1 setblock ~ ~ ~ dbc:top_table_oak
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_birch -1 setblock ~1 ~ ~ dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_birch -1 setblock ~-1 ~ ~ dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_birch -1 setblock ~1 ~ ~ dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_birch -1 setblock ~ ~ ~1 dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_birch -1 setblock ~ ~ ~-1 dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_birch -1 setblock ~ ~ ~1 dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_birch -1 setblock ~ ~ ~ dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_birch -1 setblock ~ ~ ~ dbc:top_table_birch
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_birch -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_birch -1 setblock ~ ~ ~ dbc:top_table_birch
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_spruce -1 setblock ~1 ~ ~ dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_spruce -1 setblock ~-1 ~ ~ dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_spruce -1 setblock ~1 ~ ~ dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_spruce -1 setblock ~ ~ ~1 dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_spruce -1 setblock ~ ~ ~-1 dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_spruce -1 setblock ~ ~ ~1 dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_spruce -1 setblock ~ ~ ~ dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_spruce -1 setblock ~ ~ ~ dbc:top_table_spruce
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_spruce -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_spruce -1 setblock ~ ~ ~ dbc:top_table_spruce
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_crimson -1 setblock ~1 ~ ~ dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_crimson -1 setblock ~-1 ~ ~ dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_crimson -1 setblock ~1 ~ ~ dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_crimson -1 setblock ~ ~ ~1 dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_crimson -1 setblock ~ ~ ~-1 dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_crimson -1 setblock ~ ~ ~1 dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_crimson -1 setblock ~ ~ ~ dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_crimson -1 setblock ~ ~ ~ dbc:top_table_crimson
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_crimson -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_crimson -1 setblock ~ ~ ~ dbc:top_table_crimson
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_warped -1 setblock ~1 ~ ~ dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_warped -1 setblock ~-1 ~ ~ dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_warped -1 setblock ~1 ~ ~ dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_warped -1 setblock ~ ~ ~1 dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_warped -1 setblock ~ ~ ~-1 dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_warped -1 setblock ~ ~ ~1 dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_warped -1 setblock ~ ~ ~ dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_warped -1 setblock ~ ~ ~ dbc:top_table_warped
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_warped -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_warped -1 setblock ~ ~ ~ dbc:top_table_warped
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_dark_oak -1 setblock ~1 ~ ~ dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_dark_oak -1 setblock ~-1 ~ ~ dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_dark_oak -1 setblock ~1 ~ ~ dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_dark_oak -1 setblock ~ ~ ~1 dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_dark_oak -1 setblock ~ ~ ~-1 dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_dark_oak -1 setblock ~ ~ ~1 dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_dark_oak -1 setblock ~ ~ ~ dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_dark_oak -1 setblock ~ ~ ~ dbc:top_table_dark_oak
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_dark_oak -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_dark_oak -1 setblock ~ ~ ~ dbc:top_table_dark_oak
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_jungle -1 setblock ~1 ~ ~ dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_jungle -1 setblock ~-1 ~ ~ dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_jungle -1 setblock ~1 ~ ~ dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_jungle -1 setblock ~ ~ ~1 dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_jungle -1 setblock ~ ~ ~-1 dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_jungle -1 setblock ~ ~ ~1 dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_jungle -1 setblock ~ ~ ~ dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_jungle -1 setblock ~ ~ ~ dbc:top_table_jungle
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_jungle -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_jungle -1 setblock ~ ~ ~ dbc:top_table_jungle
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_stone -1 setblock ~1 ~ ~ dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_stone -1 setblock ~-1 ~ ~ dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_stone -1 setblock ~1 ~ ~ dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_stone -1 setblock ~ ~ ~1 dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_stone -1 setblock ~ ~ ~-1 dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_stone -1 setblock ~ ~ ~1 dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_stone -1 setblock ~ ~ ~ dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_stone -1 setblock ~ ~ ~ dbc:top_table_stone
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_stone -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_stone -1 setblock ~ ~ ~ dbc:top_table_stone
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_concrete -1 setblock ~1 ~ ~ dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_concrete -1 setblock ~-1 ~ ~ dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_concrete -1 setblock ~1 ~ ~ dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_concrete -1 setblock ~ ~ ~1 dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_concrete -1 setblock ~ ~ ~-1 dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_concrete -1 setblock ~ ~ ~1 dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_concrete -1 setblock ~ ~ ~ dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_concrete -1 setblock ~ ~ ~ dbc:top_table_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_concrete -1 setblock ~ ~ ~ dbc:top_table_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_blue_concrete -1 setblock ~1 ~ ~ dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_blue_concrete -1 setblock ~-1 ~ ~ dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_blue_concrete -1 setblock ~1 ~ ~ dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_blue_concrete -1 setblock ~ ~ ~1 dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_blue_concrete -1 setblock ~ ~ ~-1 dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_blue_concrete -1 setblock ~ ~ ~1 dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_blue_concrete -1 setblock ~ ~ ~ dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_blue_concrete -1 setblock ~ ~ ~ dbc:top_table_blue_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_blue_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_blue_concrete -1 setblock ~ ~ ~ dbc:top_table_blue_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_black_concrete -1 setblock ~1 ~ ~ dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_black_concrete -1 setblock ~-1 ~ ~ dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_black_concrete -1 setblock ~1 ~ ~ dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_black_concrete -1 setblock ~ ~ ~1 dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_black_concrete -1 setblock ~ ~ ~-1 dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_black_concrete -1 setblock ~ ~ ~1 dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_black_concrete -1 setblock ~ ~ ~ dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_black_concrete -1 setblock ~ ~ ~ dbc:top_table_black_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_black_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_black_concrete -1 setblock ~ ~ ~ dbc:top_table_black_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_brown_concrete -1 setblock ~1 ~ ~ dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_brown_concrete -1 setblock ~-1 ~ ~ dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_brown_concrete -1 setblock ~1 ~ ~ dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_brown_concrete -1 setblock ~ ~ ~1 dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_brown_concrete -1 setblock ~ ~ ~-1 dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_brown_concrete -1 setblock ~ ~ ~1 dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_brown_concrete -1 setblock ~ ~ ~ dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_brown_concrete -1 setblock ~ ~ ~ dbc:top_table_brown_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_brown_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_brown_concrete -1 setblock ~ ~ ~ dbc:top_table_brown_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_cyan_concrete -1 setblock ~1 ~ ~ dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_cyan_concrete -1 setblock ~-1 ~ ~ dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_cyan_concrete -1 setblock ~1 ~ ~ dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_cyan_concrete -1 setblock ~ ~ ~1 dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_cyan_concrete -1 setblock ~ ~ ~-1 dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_cyan_concrete -1 setblock ~ ~ ~1 dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_cyan_concrete -1 setblock ~ ~ ~ dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_cyan_concrete -1 setblock ~ ~ ~ dbc:top_table_cyan_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_cyan_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_cyan_concrete -1 setblock ~ ~ ~ dbc:top_table_cyan_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_gray_concrete -1 setblock ~1 ~ ~ dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_gray_concrete -1 setblock ~-1 ~ ~ dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_gray_concrete -1 setblock ~1 ~ ~ dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_gray_concrete -1 setblock ~ ~ ~1 dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_gray_concrete -1 setblock ~ ~ ~-1 dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_gray_concrete -1 setblock ~ ~ ~1 dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_gray_concrete -1 setblock ~ ~ ~ dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_gray_concrete -1 setblock ~ ~ ~ dbc:top_table_gray_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_gray_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_gray_concrete -1 setblock ~ ~ ~ dbc:top_table_gray_concrete
 
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:small_table_green_concrete -1 setblock ~1 ~ ~ dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-2 ~ ~ dbc:top_table_green_concrete -1 setblock ~-1 ~ ~ dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~2 ~ ~ dbc:top_table_green_concrete -1 setblock ~1 ~ ~ dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:small_table_green_concrete -1 setblock ~ ~ ~1 dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-2 dbc:top_table_green_concrete -1 setblock ~ ~ ~-1 dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~2 dbc:top_table_green_concrete -1 setblock ~ ~ ~1 dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_green_concrete -1 setblock ~ ~ ~ dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~1 ~ ~ dbc:top_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~-1 ~ ~ dbc:top_table_green_concrete -1 setblock ~ ~ ~ dbc:top_table_green_concrete
execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~ dbc:small_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~1 dbc:top_table_green_concrete -1 execute @e[r=0.1,type=dbc:help_to_detect] ~ ~ ~ detect ~ ~ ~-1 dbc:top_table_green_concrete -1 setblock ~ ~ ~ dbc:top_table_green_concrete